build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"

args:
  INS_EI_CORE_REF: "bd9039a4fe3dfff4245b6ac702a9fbbd4cd087db"
  INS_EI_CORE_BUILD: "dev73-bd9039a"
