build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"

args:
  INS_EI_CORE_REF: "a5f8ba372b67b28cfe9366cbc0c08f9571f0d821"
  INS_EI_CORE_BUILD: "dev50-a5f8ba3"
