build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"

args:
  INS_EI_CORE_REF: "b3a6a81b5f40b6b9f55582af9484bde81ce604b9"
  INS_EI_CORE_BUILD: "dev58-b3a6a81"
