name: "INS-EI TEST"
version: "0.1.0-dev.34"
slug: "ins_ei_test"
description: "INS-EI Entwicklungs- und Testinstanz – nicht für Produktivbetrieb"
startup: services
boot: auto
init: false

arch:
  - aarch64
  - amd64


ingress: true
ingress_port: 8080
panel_icon: mdi:test-tube
panel_title: "INS-EI TEST"

options:
  interval_seconds: 10
  timezone: Europe/Vienna
  mqtt_enabled: false
  mqtt_host: mqtt.ins-enertech.net
  mqtt_port: 8883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_tls: true

schema:
  interval_seconds: int(1,300)
  timezone: str
  mqtt_enabled: bool
  mqtt_host: str
  mqtt_port: int(1,65535)
  mqtt_username: str
  mqtt_password: password
  mqtt_tls: bool
