name: "INS-EI TEST"
version: "0.1.0-dev.48"
slug: "ins_ei_test"
description: "INS-EI Entwicklungs- und Testinstanz – nicht für Produktivbetrieb"
startup: services
boot: auto
init: false

arch:
  - aarch64
  - amd64


ingress: true
ingress_port: 8080
panel_icon: mdi:test-tube
panel_title: "INS-EI TEST"

options:
  interval_seconds: 10
  timezone: Europe/Vienna

schema:
  interval_seconds: int(1,300)
  timezone: str
